name: Deploy Frontend with page function

on:
  workflow_run:
    workflows: [Upstream Sync]
    types: [completed]
  push:
    tags:
      - "*"
  workflow_dispatch:

concurrency:
  group: cf-temp-email-pages-production
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: pnpm/action-setup@v5
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Deploy Frontend for ${{ github.ref_name }}
        run: |
          cd frontend/
          pnpm install --no-frozen-lockfile
          pnpm build:pages
          cd ../pages/
          pnpm install --no-frozen-lockfile
          pnpm run deploy
          echo "Deployed production for ref ${{ github.ref_name }}"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
